pipeline {
    agent any

    environment {
        JAVA_HOME = "${tool name: 'Java 11', type: 'jdk'}"
        PATH = "${JAVA_HOME}/bin:${env.PATH}"
    }

    stages {
        stage('Build') {
            steps {
                sh 'javac HelloWorld.java'
            }
        }
        
        stage('Run') {
            steps {
                sh 'java HelloWorld'
            }
        }
    }
}
