pipeline {
    agent any

    stages {
        stage('Build and Run') {
            steps {
                script {
                    def javaHome = tool name: 'Java 11', type: 'jdk'
                    def javaCompiler = "${javaHome}/bin/javac"
                    def javaRuntime = "${javaHome}/bin/java"

                    sh "${javaCompiler} HelloWorld.java"
                    sh "${javaRuntime} HelloWorld"
                }
            }
        }
    }
}
